repos:
  - repo: https://github.com/dluksza/flutter-analyze-pre-commit
    rev: "master"
    hooks:
      - id: flutter-analyze
        args: [lib/*]
  - repo: https://github.com/dluksza/flutter-analyze-pre-commit
    rev: "master"
    hooks:
      - id: dart-format
        args: [lib/*]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      -   id: trailing-whitespace
      -   id: mixed-line-ending