repos:
  - repo: https://github.com/Cretezy/dart-format-pre-commit
    rev: "master"
    hooks:
      - id: dart-format
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      -   id: trailing-whitespace
      -   id: mixed-line-ending