repos:
  - repo: https://github.com/dluksza/flutter-analyze-pre-commit
    rev: "4afcaa82fc368d40d486256bf4edba329bf667bb"
    hooks:
      - id: flutter-analyze
        args: [frontend/lib/*]
  - repo: https://github.com/dluksza/flutter-analyze-pre-commit
    rev: "4afcaa82fc368d40d486256bf4edba329bf667bb"
    hooks:
      - id: dart-format
        args: [frontend/lib/*]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      -   id: trailing-whitespace
      -   id: mixed-line-ending